# Generated by Django 3.2.2 on 2021-05-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
