# Generated by Django 3.2.3 on 2021-07-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('name', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('telephone', models.CharField(blank=True, max_length=22, null=True)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('city', models.CharField(blank=True, max_length=512, null=True)),
                ('state', models.CharField(blank=True, max_length=5, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=7, null=True)),
                ('website', models.CharField(blank=True, max_length=512, null=True)),
                ('brand', models.CharField(blank=True, max_length=512, null=True)),
                ('elite', models.CharField(blank=True, max_length=512, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
            ],
        ),
    ]
