# Generated by Django 3.2.3 on 2021-07-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20210712_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
