# Generated by Django 3.2.3 on 2021-07-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pop',
            field=models.BooleanField(default=False),
        ),
    ]
